---
name: Continuous Integration

on:
  pull_request:

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v3

    - uses: actions/checkout@v5

    - name: Check formatting
      run: terraform fmt -check

  validate-module:
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v3

    - uses: actions/checkout@v5

    - name: Run terraform init
      run: terraform init

    - name: Validate module
      run: terraform validate
